default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: alpha_desk_development

test:
  <<: *default
  database: alpha_desk_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME") { "alpha_desk_production" } %>
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  queue:
    <<: *primary_production
  cache:
    <<: *primary_production
  cable:
    <<: *primary_production
